<?php

/**
 * @file
 * Contains dgi_actions.module.
 */

use Drupal\Component\Plugin\Exception\PluginNotFoundException;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_insert().
 */
function dgi_actions_node_insert(NodeInterface $node) {
  $utils = \Drupal::service('islandora.utils');

  // Execute index reactions.
  $utils->executeNodeReactions('\Drupal\dgi_actions\Plugin\ContextReaction\MintReaction', $node);
}

/**
 * Implements hook_node_predelete().
 */
function dgi_actions_node_predelete(NodeInterface $node) {
  $utils = \Drupal::service('islandora.utils');
  \Drupal::logger('dgi_actions')->info('In the PreDelete');

  // Execute index reactions.
  $utils->executeNodeReactions('\Drupal\dgi_actions\Plugin\ContextReaction\DeleteReaction', $node);
}

/**
 * Implements hook_node_delete().
 */
function dgi_actions_node_delete(NodeInterface $node) {
  $utils = \Drupal::service('islandora.utils');
  \Drupal::logger('dgi_actions')->info('In the Delete');

  // Execute index reactions.
  $utils->executeNodeReactions('\Drupal\dgi_actions\Plugin\ContextReaction\DeleteReaction', $node);
}
