---
dgi_actions.service_data_type.handle:
  type: mapping
  label: 'Handle.net Service Data'
  mapping:
    host:
      type: uri
      label: 'Host'
      description: 'Host address for the Handle.net endpoint.'
    username:
      label: 'Username'
      type: string
      description: 'Username of the Handle administrator.'
    password:
      label: 'Password'
      type: string
      description: 'Password of the Handle administrator.'
    prefix:
      label: 'Prefix'
      type: string
      description: 'Handle prefix as specified from Handle.net.'
    suffix_field:
      label: 'Suffix'
      type: string
      description: 'Field to use as handle suffix.'

action.configuration.dgi_actions_delete_handle:
  type: dgi_actions_action_delete_base
action.configuration.dgi_actions_mint_handle:
  type: dgi_actions_action_mint_base
